{
  description = "A Kubernetes cluster of NixOS machines, declared once";

  inputs = {
    # Pinned to the branch the machine was already tracking; at migration time
    # the running system rev (d57af924f160) was this branch's HEAD.
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
  };

  outputs =
    { self, nixpkgs, ... }@inputs:
    let
      inherit (nixpkgs) lib;
      system = "x86_64-linux";

      # `nixbuild` and the flake both need this; keep them from drifting apart.
      configDir = "/home/nixos/nixos-config";

      # Which machines exist and where they are. Everything below is generated
      # from it, so a new node is one entry there and nothing here.
      raw = import ./hosts/cluster.nix;

      controlPlanes = lib.attrNames (
        lib.filterAttrs (_: node: node.role == "control-plane") raw.nodes
      );

      cluster = raw // {
        # Resolved once. Two control planes would mean two `kubeadm init`s and
        # two separate clusters on one network, which is worth refusing to
        # evaluate over rather than picking one and finding out later.
        controlPlane =
          assert lib.assertMsg (lib.length controlPlanes == 1)
            "hosts/cluster.nix must name exactly one control-plane node, found: ${lib.concatStringsSep ", " controlPlanes}";
          lib.head controlPlanes;
      };

      # What the role actually decides. k8s-cluster.nix runs `kubeadm init` and
      # k8s-worker.nix runs `kubeadm join`; a machine getting both would stand
      # up a second cluster.
      roleModule = {
        control-plane = ./modules/k8s-cluster.nix;
        worker = ./modules/k8s-worker.nix;
      };

      mkHost =
        hostName: node:
        lib.nixosSystem {
          inherit system;
          specialArgs = { inherit inputs configDir cluster; };

          modules = [
            ./modules/base.nix # boot, nix, locale, packages
            ./modules/network.nix # addresses, resolvers, wake-on-lan, firewall
            ./modules/users.nix # accounts, keys, sshd, ssh aliases
            ./modules/tools.nix # nixbuild, nixdeploy, cf-tunnel, wipe-osd
            ./modules/k8s-node.nix # containerd, kernel, the kubelet unit
            ./modules/ceph-node.nix # what Rook needs of a host

            # Generated by nixos-generate-config on the machine itself, so it
            # is the one file per host that cannot come from cluster.nix.
            ./hosts/${hostName}/hardware-configuration.nix

            roleModule.${node.role}

            { networking.hostName = hostName; }
          ]
          # Which machines run Kata is a property of the machine, not of its
          # name. It used to be `hostName == "..."`, which meant renaming a node
          # silently moved the runtime off it.
          ++ lib.optional (node.kata or false) ./modules/kata-worker.nix;
        };
    in
    {
      nixosConfigurations = lib.mapAttrs mkHost cluster.nodes;
    };
}
