#!/usr/bin/env bash
# cf-tunnel -- manage Cloudflare Tunnel connectors for this cluster.
#
# One tunnel belongs to one Cloudflare account, so serving domains from
# several accounts means several tunnels, each with its own token and its own
# connector Deployment. They all point at the same ingress controller; the
# per-hostname routing stays in Ingress objects, in git.
#
# Everything this writes goes through the GitOps repo, not straight at the
# cluster: add/remove edit files and `sync` commits them. Tokens are read from
# a hidden prompt, never echoed, never passed as an argument (which would put
# them in the process list), and never written unencrypted -- the ciphertext
# is checked for leaks and round-tripped before the script exits.
set -euo pipefail

REPO="${KUBER_INFRA_REPO:-$HOME/kuber-infrastructure}"
DIR="$REPO/infrastructure/configs/cloudflared"
AGE_KEY="${SOPS_AGE_KEY_FILE:-$HOME/.config/sops/age/keys.txt}"
NS="cloudflared"

# Pinned here rather than in each generated file, so a bump is one edit and
# `sync` rolls every connector.
IMAGE="cloudflare/cloudflared:2026.8.2"
# Both halves of the name matter: <service>.<namespace>. Dropping the
# namespace resolves nowhere and every hostname answers 502.
INGRESS_SVC="traefik.traefik.svc.cluster.local:80"

self=${0##*/}

# A token file is plaintext between being written and being encrypted. If
# anything fails in that window -- sops missing its config, a bad key, a
# Ctrl-C -- the file must not survive. Registered once, cleared by hand once
# the contents are confirmed to be ciphertext.
PARTIAL=""
_clear_partial() { if [ -n "$PARTIAL" ]; then rm -f "$PARTIAL"; fi; PARTIAL=""; }
trap _clear_partial EXIT INT TERM

die()  { printf '%s: %s\n' "$self" "$*" >&2; exit 1; }
info() { printf '  %s\n' "$*"; }

need() { command -v "$1" >/dev/null || die "$1 not found"; }

require_repo() {
  need sops; need jq
  [ -f "$AGE_KEY" ]        || die "age key missing: $AGE_KEY"
  [ -f "$REPO/.sops.yaml" ] || die "not a sops repo: $REPO"
  mkdir -p "$DIR"
}

# kubectl is optional: reading the repo works with the cluster down.
have_cluster() { command -v kubectl >/dev/null && kubectl version -o json >/dev/null 2>&1; }

valid_name() {
  printf '%s' "$1" | grep -qE '^[a-z0-9]([a-z0-9-]{0,30}[a-z0-9])?$'
}

tunnels() {
  # Names come from the token files -- a tunnel exists when its secret does.
  local f n
  for f in "$DIR"/*-token.sops.yaml; do
    [ -e "$f" ] || continue
    n=${f##*/}; n=${n%-token.sops.yaml}
    printf '%s\n' "$n"
  done
}

# ── generated files ────────────────────────────────────────────────────────

write_namespace() {
  cat > "$DIR/namespace.yaml" <<YAML
# Generated by $self. Do not edit; it is rewritten on every add and remove.
apiVersion: v1
kind: Namespace
metadata:
  name: $NS
YAML
}

write_deployment() {
  local name=$1 tunnel_id=$2
  cat > "$DIR/$name-deployment.yaml" <<YAML
# Generated by $self -- edits here are lost on the next add or remove.
#
# Connector for the "$name" tunnel. It dials out to Cloudflare and holds the
# connection open, so nothing is forwarded inward and there is no address for
# the internet to reach. Losing a node costs the replicas on it and nothing
# else; the survivors keep their connections.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-$name
  namespace: $NS
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/instance: $name
  annotations:
    cf-tunnel/id: "$tunnel_id"
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
      app.kubernetes.io/instance: $name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudflared
        app.kubernetes.io/instance: $name
    spec:
      affinity:
        podAntiAffinity:
          # Preferred, not required: on a single node a required rule would
          # leave the second replica Pending until another node exists.
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: cloudflared
                    app.kubernetes.io/instance: $name
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: cloudflared
          image: $IMAGE
          args:
            - tunnel
            # The image tag is the version pin; letting the binary replace
            # itself would put the running code out of step with git.
            - --no-autoupdate
            - --metrics=0.0.0.0:2000
            - run
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-$name-token
                  key: token
          ports:
            - name: metrics
              containerPort: 2000
          livenessProbe:
            httpGet: { path: /ready, port: metrics }
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet: { path: /ready, port: metrics }
            periodSeconds: 10
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits:   { memory: 256Mi }
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
YAML
}

write_kustomization() {
  local n
  {
    printf '# Generated by %s. Do not edit; it is rewritten on every add and remove.\n' "$self"
    printf 'apiVersion: kustomize.config.k8s.io/v1beta1\n'
    printf 'kind: Kustomization\n'
    printf 'resources:\n'
    printf '  - namespace.yaml\n'
    while read -r n; do
      [ -n "$n" ] || continue
      printf '  - %s-token.sops.yaml\n' "$n"
      printf '  - %s-deployment.yaml\n' "$n"
    done < <(tunnels | sort)
  } > "$DIR/kustomization.yaml"
}

regenerate() { write_namespace; write_kustomization; }

# ── commands ───────────────────────────────────────────────────────────────

cmd_add() {
  local name=${1:-}
  [ -n "$name" ] || die "usage: $self add <name>"
  valid_name "$name" || die "name must be lowercase letters, digits and dashes (max 32)"
  [ -e "$DIR/$name-token.sops.yaml" ] && die "tunnel '$name' already exists -- remove it first"

  cat <<TXT

Cloudflare Zero Trust dashboard:
  Networks -> Tunnels -> Create a tunnel -> Cloudflared
  Copy the long string after --token in the install command (starts with "ey").

Then, on that tunnel's Public Hostnames tab, for each domain you want served:
  Subdomain : *            (a wildcard does NOT cover the bare domain --
  Domain    : <your zone>   add a second entry with an empty subdomain for that)
  Service   : HTTP -> $INGRESS_SVC

TXT
  printf 'Paste the token for "%s" (input hidden): ' "$name"
  read -rs TOKEN; printf '\n'
  [ -n "$TOKEN" ] || die "empty token"

  # A tunnel token is base64 JSON carrying an account tag, a tunnel id and a
  # secret. Checking the shape turns a mis-paste into an error now instead of
  # a CrashLoopBackOff in ten minutes.
  local decoded tunnel_id
  decoded=$(printf '%s' "$TOKEN" | base64 -d 2>/dev/null) \
    || die "not valid base64 -- this does not look like a tunnel token"
  printf '%s' "$decoded" | jq -e 'has("a") and has("t") and has("s")' >/dev/null 2>&1 \
    || die "decoded token has no account/tunnel/secret fields"
  tunnel_id=$(printf '%s' "$decoded" | jq -r '.t')
  printf '%s' "$tunnel_id" | grep -qE '^[0-9a-f-]{36}$' || die "tunnel id is not a uuid"
  unset decoded

  # Refuse to register the same tunnel twice under two names -- two connector
  # sets on one tunnel is confusing rather than redundant.
  local other
  while read -r other; do
    [ -n "$other" ] || continue
    grep -q "cf-tunnel/id: \"$tunnel_id\"" "$DIR/$other-deployment.yaml" 2>/dev/null \
      && die "that tunnel is already registered as '$other'"
  done < <(tunnels)

  local out="$DIR/$name-token.sops.yaml"
  PARTIAL="$out"
  umask 077
  cat > "$out" <<YAML
# Authenticates the "$name" connector to one specific tunnel. Encrypted with
# the cluster age key; kustomize-controller decrypts it in-cluster, so the
# plaintext never reaches git. Managed by $self.
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-$name-token
  namespace: $NS
type: Opaque
stringData:
  token: $TOKEN
YAML

  # --config explicitly: sops looks for .sops.yaml from the working
  # directory upward, not from the file it is encrypting, so running this
  # from anywhere but the repo would silently find no creation rules.
  SOPS_AGE_KEY_FILE="$AGE_KEY" sops --config "$REPO/.sops.yaml" \
    --encrypt --in-place "$out"

  # Did any of it survive in the clear? Compare a slice, so the token is never
  # re-expanded into a search pattern.
  if grep -qF -- "${TOKEN:8:24}" "$out"; then
    rm -f "$out"; die "plaintext found in the encrypted file -- removed it, nothing written"
  fi
  grep -q 'ENC\[AES256_GCM' "$out" || { rm -f "$out"; die "no ciphertext produced"; }

  # And does it come back? sops re-emits with its own indentation, so match
  # loosely rather than on a fixed number of spaces.
  local back
  back=$(SOPS_AGE_KEY_FILE="$AGE_KEY" sops --config "$REPO/.sops.yaml" -d "$out" 2>/dev/null \
    | sed -nE 's/^[[:space:]]*token:[[:space:]]*//p')
  [ "$back" = "$TOKEN" ] || { rm -f "$out"; die "round-trip decrypt did not return the token"; }
  unset TOKEN back
  PARTIAL=""
  chmod 644 "$out"

  write_deployment "$name" "$tunnel_id"
  regenerate

  echo
  info "registered '$name'  (tunnel $tunnel_id)"
  info "files: ${DIR#$REPO/}/$name-{token.sops.yaml,deployment.yaml}"
  echo
  info "next: $self sync"
}

cmd_remove() {
  local name=${1:-}
  [ -n "$name" ] || die "usage: $self remove <name>"
  [ -e "$DIR/$name-token.sops.yaml" ] || die "no such tunnel: $name"

  printf 'Remove connector "%s" from the cluster? The tunnel itself stays in\n' "$name"
  printf 'Cloudflare -- delete it there too, or it lingers with no connector.\n'
  printf 'Type the name to confirm: '
  read -r confirm
  [ "$confirm" = "$name" ] || die "not confirmed, nothing changed"

  rm -f "$DIR/$name-token.sops.yaml" "$DIR/$name-deployment.yaml"
  regenerate
  echo
  info "removed '$name' from the repo"
  info "next: $self sync   (Flux prunes the Deployment and Secret)"
}

cmd_list() {
  local n found=0 live="-" id
  printf '%-16s %-38s %s\n' "NAME" "TUNNEL ID" "CONNECTORS"
  while read -r n; do
    [ -n "$n" ] || continue
    found=1
    id=$(sed -nE 's/.*cf-tunnel\/id: "([^"]+)".*/\1/p' "$DIR/$n-deployment.yaml" 2>/dev/null)
    if have_cluster; then
      live=$(kubectl -n "$NS" get deploy "cloudflared-$n" \
        -o jsonpath='{.status.readyReplicas}/{.spec.replicas}' 2>/dev/null) || live="not deployed"
      [ "$live" = "/" ] && live="0/?"
      [ -z "$live" ] && live="not deployed"
    fi
    printf '%-16s %-38s %s\n' "$n" "${id:-?}" "$live"
  done < <(tunnels | sort)
  [ "$found" = 1 ] || info "(no tunnels registered)"
}

cmd_status() {
  local name=${1:-}
  if [ -z "$name" ]; then cmd_list; return; fi
  [ -e "$DIR/$name-token.sops.yaml" ] || die "no such tunnel: $name"
  have_cluster || die "cluster not reachable"

  echo "=== deployment ==="
  kubectl -n "$NS" get deploy "cloudflared-$name" 2>&1 | sed 's/^/  /'
  echo
  echo "=== pods ==="
  kubectl -n "$NS" get pods -l "app.kubernetes.io/instance=$name" -o wide 2>&1 | sed 's/^/  /'
  echo
  echo "=== connection registered? ==="
  # This line is the one that proves the tunnel is actually up. Its absence
  # with a Running pod means it reached Cloudflare and was refused -- usually
  # a token for a tunnel that has been deleted.
  kubectl -n "$NS" logs -l "app.kubernetes.io/instance=$name" --tail=200 2>/dev/null \
    | grep -iE "registered tunnel connection|unregistered|failed to (connect|serve)|error" \
    | tail -8 | sed 's/^/  /' || info "(no matching log lines)"
}

cmd_verify() {
  local n out back rc=0
  while read -r n; do
    [ -n "$n" ] || continue
    out="$DIR/$n-token.sops.yaml"
    if ! grep -q 'ENC\[AES256_GCM' "$out"; then
      printf '  %-16s FAIL  not encrypted\n' "$n"; rc=1; continue
    fi
    back=$(SOPS_AGE_KEY_FILE="$AGE_KEY" sops --config "$REPO/.sops.yaml" -d "$out" 2>/dev/null \
      | sed -nE 's/^[[:space:]]*token:[[:space:]]*//p')
    if [ -z "$back" ]; then
      printf '  %-16s FAIL  cannot decrypt with %s\n' "$n" "${AGE_KEY##*/}"; rc=1; continue
    fi
    if ! printf '%s' "$back" | base64 -d 2>/dev/null | jq -e 'has("t")' >/dev/null 2>&1; then
      printf '  %-16s FAIL  decrypts, but is not a tunnel token\n' "$n"; rc=1; continue
    fi
    printf '  %-16s ok    decrypts and is well-formed\n' "$n"
    unset back
  done < <(tunnels | sort)
  [ "$rc" = 0 ] || die "one or more tokens failed verification"
}

cmd_sync() {
  need git
  cd "$REPO"
  git add -A -- "infrastructure/configs/cloudflared" >/dev/null

  if git diff --cached --quiet -- "infrastructure/configs/cloudflared"; then
    info "nothing to commit"
  else
    git diff --cached --name-status -- "infrastructure/configs/cloudflared" | sed 's/^/  /'
    git commit -q -m "Update Cloudflare Tunnel connectors

Generated by $self." -- "infrastructure/configs/cloudflared"
    git push -q origin HEAD && info "pushed"
  fi

  if have_cluster && command -v flux >/dev/null; then
    flux reconcile kustomization infrastructure-configs --with-source 2>&1 | tail -2 | sed 's/^/  /'
  else
    info "(flux or cluster unavailable -- Flux will pick it up on its own interval)"
  fi
}

# ── route ──────────────────────────────────────────────────────────────────
# Publishing a hostname needs two things done at Cloudflare, not in the
# cluster: a rule on the tunnel saying where that hostname goes, and a DNS
# record pointing the name at the tunnel. Both need an API token with
# Tunnel:Edit and DNS:Edit.
#
# That token is asked for each time and never written down. It is powerful
# enough to repoint mail for the whole zone, and this is a rare operation --
# storing it would be trading a real risk for a small convenience.

CF_API="https://api.cloudflare.com/client/v4"

# Two credentials, each kept to what it already has.
#
# The DNS-01 token cert-manager uses is stored in this repo and already holds
# Zone:Read and DNS:Edit -- exactly what is needed to find the zone and write
# the record. Reusing it means the token typed in at the prompt needs one
# permission and no more: Account : Cloudflare Tunnel : Edit. Nothing has to
# be widened to publish a hostname.
_cf() { # _cf <method> <path> [body] -- uses the stored DNS token
  _cf_as "$DNSTOK" "$@"
}

_cfa() { # _cfa <method> <path> [body] -- uses the token typed in at the prompt
  _cf_as "$ADMIN" "$@"
}

_cf_as() {
  local tok=$1 method=$2 path=$3 body=${4:-}
  if [ -n "$body" ]; then
    curl -sS -m 30 -X "$method" -H "Authorization: Bearer $tok" \
      -H "Content-Type: application/json" --data "$body" "$CF_API$path"
  else
    curl -sS -m 30 -X "$method" -H "Authorization: Bearer $tok" "$CF_API$path"
  fi
}

_cf_ok() { jq -e '.success == true' >/dev/null 2>&1; }

cmd_route() {
  local name=${1:-} host=${2:-}
  local service=${3:-"http://$INGRESS_SVC"}
  [ -n "$name" ] && [ -n "$host" ] || die "usage: $self route <tunnel> <hostname> [service-url]"
  [ -e "$DIR/$name-deployment.yaml" ] || die "no such tunnel: $name"

  local tunnel_id
  tunnel_id=$(sed -nE 's/.*cf-tunnel\/id: "([^"]+)".*/\1/p' "$DIR/$name-deployment.yaml")
  [ -n "$tunnel_id" ] || die "cannot read the tunnel id out of $name-deployment.yaml"

  local dnsfile="$REPO/infrastructure/configs/cloudflare-api-token.sops.yaml"
  [ -f "$dnsfile" ] || die "the stored DNS token is missing: ${dnsfile#$REPO/}"
  DNSTOK=$(SOPS_AGE_KEY_FILE="$AGE_KEY" sops --config "$REPO/.sops.yaml" -d "$dnsfile" 2>/dev/null \
    | sed -nE 's/^[[:space:]]*api-token:[[:space:]]*//p')
  [ -n "$DNSTOK" ] || die "cannot decrypt the stored DNS token"
  _cf GET /user/tokens/verify | _cf_ok || die "the stored DNS token is not valid any more"

  printf 'API token with Account : Cloudflare Tunnel : Edit (input hidden): '
  read -rs ADMIN; printf '\n'
  [ -n "$ADMIN" ] || die "empty token"
  _cfa GET /user/tokens/verify | _cf_ok || die "token rejected by Cloudflare"

  # Which zone does this hostname belong to? Take the longest zone the token
  # can see that the hostname ends with, so a.b.example.com lands in
  # b.example.com rather than example.com when both exist.
  local zones zone zone_id
  zones=$(_cf GET "/zones?per_page=100")
  printf '%s' "$zones" | _cf_ok || die "cannot list zones with this token"

  # An empty list here is not "no such zone" -- it is almost always a missing
  # permission. Listing zones needs Zone : Zone : Read, which is separate from
  # Zone : DNS : Edit; a token with only the latter can rewrite records in a
  # zone it is told the id of, and cannot find out that the zone exists.
  if [ "$(printf '%s' "$zones" | jq '.result | length')" = "0" ]; then
    die "the stored DNS token can no longer list zones -- it needs Zone : Zone : Read"
  fi
  zone=$(printf '%s' "$zones" | jq -r --arg h "$host" '
    [.result[].name | select($h | endswith("." + .) or . == $h)]
    | sort_by(length) | reverse | .[0] // empty')
  [ -n "$zone" ] || die "none of the $(printf '%s' "$zones" | jq '.result | length') zones this token can see matches $host"
  zone_id=$(printf '%s' "$zones" | jq -r --arg z "$zone" '.result[] | select(.name==$z) | .id')

  # Guardrails. The apex and www carry the live site here, and repointing
  # either at the tunnel takes it down. Refuse rather than warn.
  [ "$host" = "$zone" ] && die "refusing: $host is the zone apex -- that is where the live site is"
  [ "$host" = "www.$zone" ] && die "refusing: www is the live site"

  echo
  info "tunnel  $name ($tunnel_id)"
  info "zone    $zone"
  info "host    $host"
  info "service $service"
  echo

  # Snapshot first. Anything this does to DNS should be visible afterwards as
  # a diff, not taken on trust.
  local before after tmp
  tmp=$(mktemp -d); trap 'rm -rf "$tmp"' RETURN
  before="$tmp/before.txt"; after="$tmp/after.txt"
  _cf GET "/zones/$zone_id/dns_records?per_page=200" \
    | jq -r '.result[] | "\(.type)\t\(.name)\t\(.content)"' | sort > "$before"
  info "$(wc -l < "$before") DNS records before"

  # ── the tunnel rule ──
  # The ingress list is ordered and its last entry must be a catch-all, so
  # insert ahead of that rather than appending.
  local cfg new_ingress
  cfg=$(_cfa GET "/accounts/$(printf '%s' "$zones" | jq -r '.result[0].account.id')/cfd_tunnel/$tunnel_id/configurations")
  printf '%s' "$cfg" | _cf_ok || die "cannot read the tunnel configuration -- does the typed-in token have Account : Cloudflare Tunnel : Edit?"

  new_ingress=$(printf '%s' "$cfg" | jq --arg h "$host" --arg s "$service" '
    (.result.config.ingress // []) as $cur
    | [ $cur[] | select((.hostname // "") != $h) ]                 # replace any existing rule for this host
    | [ .[] | select(has("hostname")) ]                            # keep only hostname rules
    | . + [{hostname: $h, service: $s}]
    | . + [{service: "http_status:404"}]                           # catch-all, must be last
  ')

  local acct; acct=$(printf '%s' "$zones" | jq -r '.result[0].account.id')
  _cfa PUT "/accounts/$acct/cfd_tunnel/$tunnel_id/configurations" \
    "$(jq -n --argjson ing "$new_ingress" '{config: {ingress: $ing}}')" | _cf_ok \
    || die "failed to update the tunnel configuration"
  info "tunnel rule set"

  # ── the DNS record ──
  local existing rec_id
  existing=$(_cf GET "/zones/$zone_id/dns_records?name=$host")
  rec_id=$(printf '%s' "$existing" | jq -r '.result[0].id // empty')
  local body
  body=$(jq -n --arg h "$host" --arg c "$tunnel_id.cfargotunnel.com" \
    '{type:"CNAME", name:$h, content:$c, proxied:true, comment:"cf-tunnel"}')
  if [ -n "$rec_id" ]; then
    _cf PATCH "/zones/$zone_id/dns_records/$rec_id" "$body" | _cf_ok || die "failed to update the DNS record"
    info "DNS record updated"
  else
    _cf POST "/zones/$zone_id/dns_records" "$body" | _cf_ok || die "failed to create the DNS record"
    info "DNS record created"
  fi

  _cf GET "/zones/$zone_id/dns_records?per_page=200" \
    | jq -r '.result[] | "\(.type)\t\(.name)\t\(.content)"' | sort > "$after"

  unset ADMIN DNSTOK
  echo
  echo "  DNS changes:"
  # Collect first, then decide. Piping diff straight into the test reports
  # "no changes" whenever there are some: diff exits 1 when files differ, and
  # pipefail makes that the status of the whole pipeline.
  local changes
  changes=$(diff -u "$before" "$after" | grep -E '^[+-][^+-]' || true)
  if [ -n "$changes" ]; then
    printf '%s\n' "$changes" | sed 's/^/    /'
  else
    echo "    (none -- the record already matched)"
  fi
  echo
  # A wildcard is not a name anything can fetch, and stripping the star off it
  # leaves the apex -- which here is somebody else's site.
  case "$host" in
    \*.*) info "check it with:  curl -I https://<anything>.${host#\*.}" ;;
    *)    info "check it with:  curl -I https://$host" ;;
  esac
}

usage() {
  cat <<TXT
$self -- manage Cloudflare Tunnel connectors

  $self add <name>       register a tunnel token (hidden input) and write its connector
  $self remove <name>    drop a connector from the repo
  $self list             registered tunnels and how many connectors are up
  $self status [name]    deployment, pods, and whether the tunnel actually connected
  $self verify           decrypt every token and check it is well-formed
  $self route <t> <host> publish a hostname through a tunnel (asks for a Tunnel:Edit token)
  $self sync             commit, push, and tell Flux to reconcile

One tunnel per Cloudflare account. All connectors point at the same ingress
controller; per-hostname routing stays in Ingress objects.

  repo   $REPO
  age    $AGE_KEY
  image  $IMAGE
TXT
}

case "${1:-}" in
  add)    require_repo; shift; cmd_add    "$@" ;;
  remove|rm) require_repo; shift; cmd_remove "$@" ;;
  list|ls)   require_repo; shift; cmd_list   "$@" ;;
  status)    require_repo; shift; cmd_status "$@" ;;
  verify)    require_repo; shift; cmd_verify "$@" ;;
  route)     require_repo; shift; cmd_route  "$@" ;;
  sync)      require_repo; shift; cmd_sync   "$@" ;;
  ""|-h|--help|help) usage ;;
  *) die "unknown command: $1 (try --help)" ;;
esac
